<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class TherapistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('therapists')->insert([
            [
                'id'                    => '1',
                'name'                  => 'dr. Keanu Reeves, S.Td, L.Td',
                'username'              => 'keanu',
                'photo_name'            => 'sample_therapist_01',
                'photo_path'            => 'dummy/sample_therapist_01.png',
                'province_id'           => '33',
                'regency_id'            => '3313',
                'district_id'           => '3313150',
                'village'               => 'Mojogedang',
                'address'               => 'Jalan Setapak, RT 03 RW 02, Dusun Mojogedang',
                'address_origin'        => 'Jl. Palem RT 05 RW IX Cemani, Grogol, Sukoharjo, Jawa Tengah 57552',
                'religion'              => 'Islam',
                'phone'                 => '81390990019',
                'whatsapp'              => '81390990019',
                'year_of_graduate'      => '2020',
                'str_number'            => '1111-2222-3333-4444',
                'job_place'             => 'RS. Massachusetts',
                'job_hour'              => "Senin-Jum'at jam 08.00 s.d. 15.00 WIB",
                'job_address'           => '77 Massachusetts Ave, Cambridge, MA 02139, United States 57752',
                'source'                => 'Instagram',
                'email'                 => 'keanu.reeves@gmail.com',
                'email_verified_at'     => now(),
                'blocked'               => FALSE,
                'blocked_at'            => null,
                'password'              => Hash::make('12345678'),
                'edu_history'           => 'Edu history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'workshop_history'      => 'Workshop history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'internship_experience' => 'Internship experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'job_experience'        => 'Job experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'equipment'             => 'Equipment, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'max_distance'          => '20',
                'max_duration'          => '60',
                'homecare'              => 'Homecare, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'bank_name'             => 'BNI',
                'bank_account'          => 'Keanu Reeves',
                'account_number'        => '777 888 999 666',
                'status'                => 'Disetujui',
                'step'                  => '0',
                'remember_token'        => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => '2',
                'name'                  => 'dr. Mikaella Megan Fox, S.Td, L.Td',
                'username'              => 'mikaella',
                'photo_name'            => 'sample_therapist_02',
                'photo_path'            => 'dummy/sample_therapist_02.png',
                'province_id'           => '33',
                'regency_id'            => '3313',
                'district_id'           => '3313150',
                'village'               => 'Mojogedang',
                'address'               => 'Jalan Setapak, RT 03 RW 02, Dusun Mojogedang',
                'address_origin'        => 'Jl. Palem RT 05 RW IX Cemani, Grogol, Sukoharjo, Jawa Tengah 57552',
                'religion'              => 'Islam',
                'phone'                 => '81390990018',
                'whatsapp'              => '81390990018',
                'year_of_graduate'      => '2020',
                'str_number'            => '1111-2222-3333-5555',
                'job_place'             => 'RS. Massachusetts',
                'job_hour'              => "Senin-Jum'at jam 08.00 s.d. 15.00 WIB",
                'job_address'           => '77 Massachusetts Ave, Cambridge, MA 02139, United States 57752',
                'source'                => 'Instagram',
                'email'                 => 'mikaella.fox@gmail.com',
                'email_verified_at'     => now(),
                'blocked'               => FALSE,
                'blocked_at'            => null,
                'password'              => Hash::make('12345678'),
                'edu_history'           => 'Edu history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'workshop_history'      => 'Workshop history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'internship_experience' => 'Internship experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'job_experience'        => 'Job experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'equipment'             => 'Equipment, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'max_distance'          => '20',
                'max_duration'          => '60',
                'homecare'              => 'Homecare, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'bank_name'             => 'Mandiri',
                'bank_account'          => 'Mikaella Megan Fox',
                'account_number'        => '777 888 999 444',
                'status'                => 'Disetujui',
                'step'                  => '0',
                'remember_token'        => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => '3',
                'name'                  => 'dr. Jung Eunbi, S.Td, L.Td',
                'username'              => 'eunbi',
                'photo_name'            => 'sample_therapist_03',
                'photo_path'            => 'dummy/sample_therapist_03.png',
                'province_id'           => '33',
                'regency_id'            => '3313',
                'district_id'           => '3313150',
                'village'               => 'Mojogedang',
                'address'               => 'Jalan Setapak, RT 03 RW 02, Dusun Mojogedang',
                'address_origin'        => 'Jl. Palem RT 05 RW IX Cemani, Grogol, Sukoharjo, Jawa Tengah 57552',
                'religion'              => 'Islam',
                'phone'                 => '81390990017',
                'whatsapp'              => '81390990017',
                'year_of_graduate'      => '2020',
                'str_number'            => '1111-2222-3333-4444',
                'job_place'             => 'RS. Massachusetts',
                'job_hour'              => "Senin-Jum'at jam 08.00 s.d. 15.00 WIB",
                'job_address'           => '77 Massachusetts Ave, Cambridge, MA 02139, United States 57752',
                'source'                => 'Instagram',
                'email'                 => 'jung.eunbi@gmail.com',
                'email_verified_at'     => now(),
                'blocked'               => FALSE,
                'blocked_at'            => null,
                'password'              => Hash::make('12345678'),
                'edu_history'           => 'Edu history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'workshop_history'      => 'Workshop history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'internship_experience' => 'Internship experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'job_experience'        => 'Job experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'equipment'             => 'Equipment, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'max_distance'          => '20',
                'max_duration'          => '60',
                'homecare'              => 'Homecare, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'bank_name'             => 'Mandiri',
                'bank_account'          => 'Jung Eunbi',
                'account_number'        => '777 888 999 3333',
                'status'                => 'Disetujui',
                'step'                  => '0',
                'remember_token'        => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => '4',
                'name'                  => 'dr. Sebastian Stan, S.Td, L.Td',
                'username'              => 'sebastian',
                'photo_name'            => 'sample_therapist_04',
                'photo_path'            => 'dummy/sample_therapist_04.png',
                'province_id'           => '33',
                'regency_id'            => '3313',
                'district_id'           => '3313150',
                'village'               => 'Mojogedang',
                'address'               => 'Jalan Setapak, RT 03 RW 02, Dusun Mojogedang',
                'address_origin'        => 'Jl. Palem RT 05 RW IX Cemani, Grogol, Sukoharjo, Jawa Tengah 57552',
                'religion'              => 'Islam',
                'phone'                 => '81390990016',
                'whatsapp'              => '81390990016',
                'year_of_graduate'      => '2020',
                'str_number'            => '1111-2222-3333-2222',
                'job_place'             => 'RS. Massachusetts',
                'job_hour'              => "Senin-Jum'at jam 08.00 s.d. 15.00 WIB",
                'job_address'           => '77 Massachusetts Ave, Cambridge, MA 02139, United States 57752',
                'source'                => 'Instagram',
                'email'                 => 'sebastian.stan@gmail.com',
                'email_verified_at'     => now(),
                'blocked'               => FALSE,
                'blocked_at'            => null,
                'password'              => Hash::make('12345678'),
                'edu_history'           => 'Edu history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'workshop_history'      => 'Workshop history, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'internship_experience' => 'Internship experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'job_experience'        => 'Job experience, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'equipment'             => 'Equipment, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'max_distance'          => '20',
                'max_duration'          => '60',
                'homecare'              => 'Homecare, lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
                'bank_name'             => 'Danamon',
                'bank_account'          => 'Sebastian Stan',
                'account_number'        => '777 888 999 2222',
                'status'                => 'Disetujui',
                'step'                  => '0',
                'remember_token'        => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ]
        ]);
    }
}
